### ISSUE TITLE
site_path_prefix does not change tag links

### ISSUE THREAD

**Issue by sean369see** [samim23/flow#3]
In .env I have set my site_url to https://xuanseanli.com/blog and tag buttons in the tag page understandably point to https://xuanseanli.com/blog/tag/<name of tag>.

However tags added to each individual post point to https://xuanseanli.com/tag/<name of tag> which is above the blog directory. Changing **site_path_prefix** in .env does not change this behavior.

**Comment by samim23** [comment]
thank you for flagging this. The changes have been implemented so that setting "site_path_prefix" to for example "/blog" will be respected. git pull and check the updated readme. Let me know if this works for you!

**Comment by sean369see** [comment]
In the published index.html, the system is creating links with /C:/Program Files/Git/ inserted after the site_url like this:

`https://xuanseanli.com/C:/Program Files/Git/blog/static/css/style.css`

When creating a new post, all previous posts disappear.

**Comment by samim23** [comment]
Nice catch! seems to be a windows issue i did not notice (on linux). Pushed a potential fix, please check and let me know!

**Comment by samim23** [comment]
"When creating a new post, all previous posts disappear." this is very strange. if you still experience this issue, i would recommend using the old version from git for now, until its properly diagnosed and fixed. sorry about this.

**Comment by sean369see** [comment]
This is what is generated in the index.html in build folder after publishing:

```
<!doctype html>
<html lang="en" dir="ltr">
<head>
  <meta charset="UTF-8">
  <title>XSL - blog</title>
<meta name="description" content="knowledge junction points">  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="Xuan (Sean) Li"><meta name="theme-color" content="#ffffff">
  <meta name="format-detection" content="telephone=no">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta property="og:title" content="XSL - blog" />
  <meta property="og:description" content="knowledge junction points" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="https://xuanseanli.com" />  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@ " />
  <meta name="twitter:title" content="XSL - blog" />
  <meta name="twitter:description" content="knowledge junction points" />
  <link rel="alternate" type="application/rss+xml" title="RSS Feed" href="https://xuanseanli.com/Git/blog/rss.xml" />
  <link rel='icon' href="https://xuanseanli.com/Git/blog/static/img/favicon.png" type="image/png"/>
  <link rel="dns-prefetch" href="https://xuanseanli.com">  <link rel=stylesheet type=text/css href="https://xuanseanli.com/Git/blog/static/css/style.css">
  <link rel="preload" href="https://xuanseanli.com/Git/blog/static/js/client.js" as="script">
  <script src="https://xuanseanli.com/Git/blog/static/js/vendor/mathjax/es5/tex-mml-chtml.js"></script></head>
<body>
  <div id="site">    <header id="top-container">
      <div id="site_logo"><h1><a id="site_logo_icon" href="https://xuanseanli.com/Git/blog/">XSL - blog</a></h1></div><div class="post_static_container">
        <div class="post_static">
          <a title="Tags" href="https://xuanseanli.com/Git/blog/tag/">tags</a>
        </div>
        <div class="post_static"><a title="About" href="/p/about/">about</a></div>
      </div>    </header>    <main>       <ul id="posts"><li class="content_divider"></li><li class="h-entry">
        <div class="post_meta"><div class="p-author h-card post_user_icon"></div>
            <h2 class="post_date_title"><a rel="bookmark" class="post_date" href="https://xuanseanli.com/Git/blog/p/2025-05-14-test-posthealth/">test posthealth</a></h2>
            <a class="post_date" href="https://xuanseanli.com/Git/blog/p/2025-05-14-test-posthealth/"><time class="dt-published" datetime="2025-05-14 11:14:07">2025-05-14 11:14:07</time></a></div><div class="e-content content_main">
          <p>test post</p><p><a href="C:/Program Files/Git/blog/tag/health">#health</a></p>
        </div><div class="content_divider"></div>
      </li></ul><div id="pagination_container"><a rel="next" id="pagination_previous" data-num="0" href="https://xuanseanli.com/Git/blog/archive/0.html">« Previous</a></div> <p id="loading">
	<img
		src="https://xuanseanli.com/Git/blog/static/img/loading.gif"
		alt="Loading..."
		width="80"
	/>
</p>
</main>
    <footer id="footer"></footer>
    <script src="https://xuanseanli.com/Git/blog/static/js/client.js"></script>
  </div>
</body>
</html>
```

**Comment by samim23** [comment]
thanks for the pointers. this windows issue is naughty. commited another round of fixes. please try

**Comment by sean369see** [comment]
Still see the insertion of 'Git'. 

view-source:https://xuanseanli.com/blog/

```
<div id="site" data-site-path-prefix="C:/Program Files/Git/blog/">
<a href="/Program Files/Git/blog/tag/test">#test</a>
```

**Comment by samim23** [comment]
Ok interesting... i've commited yet another fix. please check

**Comment by sean369see** [comment]
I no longer see the windows paths. Seems like the tag in the test post does not show the button styling. Styling is still applied in the old post.

**Comment by samim23** [comment]
ok fix it up for that hashtag thing. was all related to windows path handling. please test

**Comment by sean369see** [comment]
Works now! Windows! I'll migrate my old posts and test.

**Comment by samim23** [comment]
nice! btw. you should be able to restore your old blog posts as well... maybejsut needs some path updating in there... not sure. but its possible for sure

**Comment by sean369see** [comment]
Is their a way to configure the uploads folder to be in the same directory as tags now?

**Comment by samim23** [comment]
yes, this is possible by adjusting the settings to match the site path prefix.
Currently, the uploads are configured in app/settings.py with these settings:

```
 FTP settings
server_ftp_media_path: str = "/public_html/static/upload/"
server_ftp_media_site_path: str = "https://samim.io/static/upload/"

# File paths
local_upload_path: Path = Path("upload/")
```

If you want uploads to be in the same directory structure as tags (using the site_path_prefix), you need to modify the .env file to update these paths.

Edit the .env file and add/modify these settings:

```
 For local storage
LOCAL_UPLOAD_PATH=build/static/upload/

# For FTP uploads
SERVER_FTP_MEDIA_PATH=/public_html/blog/static/upload/
SERVER_FTP_MEDIA_SITE_PATH=https://xuanseanli.com/blog/static/upload
```

Ensure the upload directory exists:

`mkdir -p build/static/upload/`

This way the uploads will follow the same path structure with their site_path_prefix of /blog/.
For the uploaded images to actually appear with the correct URLs, the app already uses server_ftp_media_site_path which should contain the full URL. By setting it to include the /blog/ subdirectory, the image URLs will be properly constructed.
The system is designed so that:
local_upload_path controls where files are stored locally
server_ftp_media_path controls where they're uploaded on the FTP server
server_ftp_media_site_path controls the URL prefix used when linking to them
By setting all three to use the /blog/ prefix consistently, uploads will work correctly within the subdirectory structure.

**Comment by sean369see** [comment]
Thanks. Testing and getting this error about failing to load posts from archive.

            
GET https://xuanseanli.com/archive/0.html 404 (Not Found)
loadPageFromURL @ client.js:362
loadPage @ client.js:462
infiniteScroll @ client.js:484
(anonymous) @ client.js:559
blog/:1 

But the link in index appears correct. 

`
<a rel="next" id="pagination_previous" data-num="0" href="https://xuanseanli.com/blog/archive/0.html">« Previous</a>
`

**Comment by samim23** [comment]
fix is up, was again the path windows thing

**Comment by sean369see** [comment]
Still getting this in the UI. 

Failed to load page: ReferenceError: _paq is not defined
    at loadPageFromURL (client.js:367:4)

**Comment by samim23** [comment]
fixed, please check. Note that these errors are fixed in javascript, so maybe need to hardrefresh your browser

**Comment by sean369see** [comment]
Testing image in post and getting Not allowed to load local resource: blob:

The src for the image is incorrect. 
`<img src="blob:http://127.0.0.1:2323/ed639668-c50f-4520-88fb-8bcff520c075" alt="">
`
In the UI the images for the older posts do not appear but do appear after publishing to server. 

This is after I reverted to stock settings for the upload in .env

**Comment by samim23** [comment]
nice find. committed a fix. haven't tested it properly though cause its late here. Very much appreciate your patience and help!

**Comment by sean369see** [comment]
Should the static directory path be also changed from root if site_path_prefix is set to /blog/ etc.? I still have a static folder in root otherwise I get missing fonts.
